import { ArchetypeSlug, VisualScores, PsychScores } from "@/types";

export const ARCHETYPE_BASE_SCORES: Record<
  ArchetypeSlug,
  { visual: VisualScores; psych: PsychScores }
> = {
  modern_european: {
    visual: {
      formal: 55,
      classic: 70,
      minimalist: 75,
      refined: 75,
      practical: 65,
      urban: 95,
      visibility: 25,
      tailored: 65,
    },
    psych: {
      adventure: 50,
      status: 60,
      creativity: 55,
      tradition: 40,
      practicality: 70,
      individualism: 50,
      social: 50,
    },
  },
  adventure: {
    visual: {
      formal: 15,
      classic: 40,
      minimalist: 50,
      refined: 20,
      practical: 100,
      urban: 5,
      visibility: 25,
      tailored: 15,
    },
    psych: {
      adventure: 100,
      status: 15,
      creativity: 40,
      tradition: 35,
      practicality: 95,
      individualism: 70,
      social: 35,
    },
  },
  old_money: {
    visual: {
      formal: 70,
      classic: 95,
      minimalist: 70,
      refined: 90,
      practical: 60,
      urban: 65,
      visibility: 20,
      tailored: 75,
    },
    psych: {
      adventure: 20,
      status: 85,
      creativity: 20,
      tradition: 95,
      practicality: 50,
      individualism: 15,
      social: 95,
    },
  },
  streetwear: {
    visual: {
      formal: 10,
      classic: 10,
      minimalist: 20,
      refined: 20,
      practical: 45,
      urban: 95,
      visibility: 90,
      tailored: 15,
    },
    psych: {
      adventure: 60,
      status: 70,
      creativity: 75,
      tradition: 10,
      practicality: 40,
      individualism: 85,
      social: 75,
    },
  },
  workwear: {
    visual: {
      formal: 20,
      classic: 70,
      minimalist: 35,
      refined: 25,
      practical: 100,
      urban: 20,
      visibility: 35,
      tailored: 25,
    },
    psych: {
      adventure: 50,
      status: 10,
      creativity: 25,
      tradition: 75,
      practicality: 100,
      individualism: 60,
      social: 45,
    },
  },
};

export const IMAGE_PROMPTS: Record<ArchetypeSlug, string[]> = {
  modern_european: [
    "Navy tailored trousers, beige overshirt, white minimalist sneakers, white T-shirt.",
    "Charcoal trousers, olive bomber jacket, fine white knit, low-profile sneakers.",
    "Stone chinos, navy merino sweater, suede sneakers, clean urban styling.",
    "Black tapered trousers, grey overshirt, white crewneck, minimalist leather sneakers.",
    "Navy lightweight jacket, beige trousers, white shirt, brown suede loafers.",
    "Olive overshirt, charcoal trousers, cream knit polo, white sneakers.",
    "Dark denim, navy chore-style jacket, grey knitwear, clean European silhouette.",
    "Beige linen overshirt, navy trousers, white sneakers, Mediterranean city style.",
    "Charcoal wool trousers, black knit polo, minimalist jacket, sleek sneakers.",
    "Cream trousers, navy knit cardigan, white T-shirt, suede loafers.",
  ],
  adventure: [
    "Forest green shell jacket, grey hiking trousers, trail shoes.",
    "Lightweight down vest, navy fleece, technical hiking pants, approach shoes.",
    "Rust fleece jacket, black trekking trousers, mountain trail sneakers.",
    "Olive rain jacket, grey base layer, cargo hiking pants, rugged trail shoes.",
    "Navy technical shell, black softshell pants, lightweight hiking boots.",
    "Grey fleece pullover, olive climbing pants, trail runners.",
    "Black insulated jacket, forest green hiking pants, technical sneakers.",
    "Rust windbreaker, charcoal trekking trousers, outdoor cap.",
    "Navy fleece vest, khaki hiking pants, trail shoes.",
    "Olive technical jacket, black trail pants, minimalist outdoor styling.",
  ],
  old_money: [
    "Navy blazer, white oxford shirt, khaki chinos, brown loafers.",
    "Cream cable-knit sweater, light blue shirt, navy trousers, loafers.",
    "Forest green sweater, beige chinos, suede loafers, classic collegiate styling.",
    "Navy cardigan, white oxford shirt, grey wool trousers, brown loafers.",
    "Burgundy sweater, khaki trousers, navy blazer, leather loafers.",
    "Tweed sport coat, cream shirt, navy chinos, suede shoes.",
    "Camel overcoat, navy sweater, grey trousers, brown loafers.",
    "Blue oxford shirt, beige chinos, navy quilted vest, loafers.",
    "Cream knit polo, navy trousers, brown belt, loafers.",
    "Navy blazer, striped shirt, white trousers, classic summer club style.",
  ],
  streetwear: [
    "Oversized black hoodie, cargo pants, chunky sneakers.",
    "Graphic T-shirt, bomber jacket, loose jeans, statement sneakers.",
    "Oversized grey sweatshirt, black cargos, high-top sneakers.",
    "Black puffer jacket, wide-leg pants, white sneakers.",
    "Boxy tee, utility vest, relaxed denim, skate sneakers.",
    "Oversized varsity jacket, hoodie, cargo trousers, sneakers.",
    "Relaxed tracksuit jacket, wide black pants, bold sneakers.",
    "White oversized tee, black cargos, crossbody bag, sneakers.",
    "Denim jacket, graphic hoodie, relaxed trousers, street sneakers.",
    "Black hoodie, olive cargo pants, chunky white sneakers.",
  ],
  workwear: [
    "Brown chore coat, raw denim, white T-shirt, leather work boots.",
    "Olive canvas jacket, flannel shirt, dark jeans, moc-toe boots.",
    "Indigo chore jacket, tan work pants, brown boots.",
    "Heavy flannel overshirt, raw denim, leather belt, work boots.",
    "Duck canvas jacket, grey sweatshirt, faded jeans, rugged boots.",
    "Denim jacket, olive work pants, white tee, brown boots.",
    "Brown utility vest, chambray shirt, raw denim, work boots.",
    "Tan chore coat, navy flannel, dark jeans, rugged leather boots.",
    "Olive field jacket, denim shirt, canvas trousers, boots.",
    "Brown work jacket, cream henley, raw denim, engineer boots.",
  ],
};
